<?php

namespace Lucinda\WebSecurity\Token;

/**
 * Produces and validates encrypted tokens for CSRF checks and authentication persistence
 *
 * Wraps a scalar payload in JSON fields for the payload (uid), client IP,
 * issue time, and expiration time, then protects it through Encryption.
 * Callers interpret the restored payload and perform identity or application
 * checks; this class does not authenticate users, store tokens, or revoke them.
 *
 * Expired tokens are rejected. Still-valid tokens exceeding a configured
 * renewal age are returned through a RegenerationException for the caller
 * to reissue rather than being regenerated by this class.
 *
 * @see Encryption
 * @see \Lucinda\WebSecurity\Detectors\CsrfToken
 * @see \Lucinda\WebSecurity\PersistenceDrivers\SynchronizerToken\PersistenceDriver
 * @see \Lucinda\WebSecurity\PersistenceDrivers\RememberMe\PersistenceDriver
 */
class SynchronizerToken
{
    private string $ip;
    private string $salt;

    /**
     * Stores the IP-binding context and shared encryption secret
     *
     * Construction does not issue a token. Encoding and decoding must use the
     * same secret and IP value. An empty IP value must be used consistently
     * when the caller disables IP binding.
     *
     * @param string $ip Client IP bound to the token, or an empty string when IP binding is disabled
     * @param string $salt Shared secret used to derive the encryption key, not a public per-token salt
     */
    public function __construct(string $ip, string $salt)
    {
        $this->ip = $ip;
        $this->salt = $salt;
    }

    /**
     * Creates an encrypted token containing the supplied payload and validity metadata
     *
     * Issue and expiration times are Unix timestamps in seconds. String payloads
     * must be valid UTF-8 for JSON encoding. Zero duration does not disable
     * expiration; the embedded expiration then equals the issue time.
     *
     * @param int|string|null $userID Identity or serialized authentication payload to store in the uid field
     * @param int $expirationTime Token lifetime in seconds from issuance, not an absolute timestamp
     * @return string Versioned encrypted token containing the JSON payload
     * @throws Exception If the payload or metadata cannot be encoded as JSON
     * @throws EncryptionException If encryption fails
     * @throws \Exception If secure random bytes for encryption cannot be generated
     */
    public function encode(int|string|null $userID, int $expirationTime=3600): string
    {
        $currentTime = time();
        $payload = ["uid"=>$userID, "ip"=>$this->ip, "time"=>$currentTime, "expiration"=>($currentTime+$expirationTime)];
        $encryption = new Encryption($this->salt);
        try {
            $json = json_encode($payload, JSON_THROW_ON_ERROR);
        } catch(\JsonException $exception) {
            throw new Exception("Token payload could not be encoded!", 0, $exception);
        }
        return $encryption->encrypt($json);
    }

    /**
     * Validates a token and restores its scalar payload or signals renewal
     *
     * Checks the encrypted envelope, JSON structure, exact IP match, and expiry
     * before evaluating token age. Expiration takes precedence over renewal.
     * This method does not issue a replacement token.
     *
     * On ordinary return, PHP-empty uid values (null, zero, "0", and "") become
     * null. A renewal exception carries the original uid before this normalization.
     * A decoded payload alone does not establish completed authentication.
     *
     * @param string $token Versioned encrypted token produced by encode()
     * @param int $maximumLifetime Renewal age in seconds; zero disables age-based renewal signaling
     * @return int|string|null Restored uid payload, or null when the stored value is empty
     * @throws EncryptionException If the encrypted envelope is malformed or cryptographic verification fails
     * @throws Exception If JSON decoding, payload structure, or IP validation fails
     * @throws ExpiredException If the current time exceeds the embedded expiration timestamp
     * @throws RegenerationException If an unexpired token exceeds the non-zero renewal age; carries its original uid
     */
    public function decode(string $token, int $maximumLifetime=0): int|string|null
    {
        $encryption = new Encryption($this->salt);
        $decryptedValue = $encryption->decrypt($token);
        try {
            $parts = json_decode($decryptedValue, true, 512, JSON_THROW_ON_ERROR);
        } catch(\JsonException $exception) {
            throw new Exception("Token payload could not be decoded!", 0, $exception);
        }

        // validate decoded json structure
        if (
            !is_array($parts)
            || !array_key_exists("uid", $parts)
            || !isset($parts["ip"], $parts["time"], $parts["expiration"])
            || (
                $parts["uid"] !== null
                && !is_int($parts["uid"])
                && !is_string($parts["uid"])
            )
            || !is_string($parts["ip"])
            || !is_int($parts["time"])
            || !is_int($parts["expiration"])
        ) {
            throw new Exception("Invalid token payload!");
        }

        // validate token
        if ($this->ip!==$parts["ip"]) {
            throw new Exception("Token was issued from a different ip!");
        }
        $currentTime = time();
        if ($currentTime > $parts["expiration"]) {
            throw new ExpiredException("Token has expired!");
        }
        if ($maximumLifetime && ($currentTime-$parts["time"])>$maximumLifetime) {
            $tre = new RegenerationException("Token needs to be regenerated!");
            $tre->setPayload($parts["uid"]);
            throw $tre;
        }

        // return user identifier
        return empty($parts["uid"]) ? null : $parts["uid"];
    }
}
