<?php

namespace Lucinda\WebSecurity;

use Lucinda\WebSecurity\DAO\OAuth2\UserInformation;

/**
 * Defines the application-supplied adapter for one OAuth2 provider
 *
 * Implementations translate the library's provider-neutral authentication
 * workflow into provider-specific authorization URLs, authorization-code
 * exchange calls, and user-information calls. Instances are injected into
 * Wrapper keyed by the provider names declared in XML.
 *
 * The surrounding workflow generates, persists, and validates OAuth2 state.
 * The service must include the supplied state in its authorization request,
 * but must not independently decide whether a callback state is valid.
 *
 * @see Wrapper::__construct()
 * @see OAuth2State
 * @see \Lucinda\WebSecurity\Security\Authentication\Oauth2
 * @see \Lucinda\WebSecurity\DAO\OAuth2\UserInformation
 */
interface OAuth2Service
{
    /**
     * Builds the provider authorization endpoint for a new login attempt
     *
     * The returned URL must send the exact supplied state value to the provider
     * so it is returned unchanged to the configured callback route.
     *
     * @param string $state Cryptographically random, provider-bound state generated by the authentication workflow
     * @return string Absolute provider authorization URL to which the caller can redirect the user
     * @throws \Throwable If provider-specific authorization URL construction fails
     */
    public function getAuthorizationCodeEndpoint(string $state): string;

    /**
     * Exchanges a provider authorization code for an access token
     *
     * Called only after the surrounding workflow has consumed a valid OAuth2
     * state and rejected provider callbacks that contain an error.
     *
     * @param string $authorizationCode Non-empty authorization code received from the provider callback
     * @return string Provider access token used to request remote user information
     * @throws \Throwable If the code is invalid, expired, already consumed, or the provider request fails
     */
    public function getAccessToken(string $authorizationCode): string;

    /**
     * Loads normalized user information from the OAuth2 provider
     *
     * @param string $accessToken Provider access token returned by getAccessToken()
     * @return UserInformation Provider identity exposed through the library-neutral user-information contract
     * @throws \Throwable If the token is rejected or the provider request or response mapping fails
     */
    public function getUserInfo(string $accessToken): UserInformation;
}
